### PR TITLE
Moa refactor browse media build item response

### LINKED ISSUE #17: Refactor in browse_media to only try to fetch data about the selected option

### PR DESCRIPTION
**Pull request by zrohacova**

### CODE REVIEW

**Review by salvija — COMMENTED** [review]
Looks good! But is it possible to fix the check other linters (yamllint) issue?

**Review by ThushiniRanasinghe1998 — DISMISSED** [review]
Adding to comments by Salvia.....Awesome work! 👍

Great job on the docs and code clarity.
Tests look solid.
Everything looks clean and well-organized.

**Review by ThushiniRanasinghe1998 — COMMENTED** [review]
Adding to comments by Salvia.....Awesome work! 👍

Great job on the docs and code clarity.
Tests look solid.
Everything looks clean and well-organized.

**Comment by moa114** [comment]
> Looks good! But is it possible to fix the check other linters (yamllint) issue?

I disabled the error, since I believe it is not a "real" error in this case. For the interested, you can read about it here: https://github.com/adrienverge/yamllint/issues/430

**Review by ThushiniRanasinghe1998 — APPROVED** [review]

**Review by linneafransson — APPROVED** [review]

**Review by salvija — APPROVED** [review]

**Comment by salvija** [comment]
There is some mypy errors left in analytics and hue, maybe it would be good to fix them before we merge this PR:
Screenshot 2023-11-17 at 15 11 21

**Comment by salvija** [comment]
Some tests are failing from the zrohacova-patch-1 branch, as soon as these issues are fixed then you can merge it again and then we can merge this branch into dev 😅

**Review by salvija — APPROVED** [review]

**Pull request merged**
