### PR TITLE
Reformatting 

### PR DESCRIPTION
**Pull request by zrohacova**

### CODE REVIEW

**Comment by moa114** [comment]
Just curious, why did you remove mazda?

**Review by salvija — COMMENTED** [review]
Ten of the CI/Run tests Python are failing, is it something that will be fixed in another PR?
Screenshot 2023-11-17 at 20 18 11

**Comment by zrohacova** [comment]
> Just curious, why did you remove mazda?

Package for pymazda was rmeoved entirely last month from the python, so then fetching it was failing

**Comment by zrohacova** [comment]
> Ten of the CI/Run tests Python are failing, is it something that will be fixed in another PR? Screenshot 2023-11-17 at 20 18 11

probably yeah, these are fails of tests that are not ours, so need to chck what is happening

**Review by salvija — APPROVED** [review]

**Pull request merged**
